---
title: "Syllabus"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'syllabus.html'))})
output: 
  html_document:
    includes:
      in_header: "favicon.html" 
---

***

Instructor: [Hongfei Li](https://www.business.uconn.edu/person/hongfei-li/) 

* Email: Hongfei.li@uconn.edu. 
* Office: BUSN 407 
* Classroom: LH 101
* Class meets: Tue/Thu 2:00-3:15 pm 
* Office Hours: Tue/Thu 12:30-1:30 pm

TA Office hours:

* Aindrila Chakraborty: Aindrila.Chakraborty@uconn.edu Thu 3:30-4:30 pm
* Yucheng Chen: Yucheng.chen@uconn.edu Tue 3:30-4:30 pm


***

# Course Description

Operations Management (OM) designs, operates and improves productive systems, by managing the function that transforms inputs (materials, machines, labor, and capital) into outputs (products and services) of greater value. As a central function area of any business organization, OM has gained increasing recognition as a source of competitive advantage, presenting great challenges as well as tremendous opportunities, for a company to succeed in today’s global business environment with the advent of information technology. In this course, students will learn what functions OM performs, why it is important, and how to make business decisions in the field of OM. We introduce both fundamental concepts and quantitative models of operations management. Topics covered in detail are decision making tools, forecasting techniques, inventory management, aggregate planning, waiting line analysis, and etc. The objective is to help students develop a systematic working knowledge of the concepts and methods related to designing and managing operations.  

***

# Course Content

Tentative subjects include:

* Decision Making Tools:
    * Decision strategy
    * Decision table
    * Decision tree
    * Review on Excel
* Forecasting:
    * One-variable forecasting: moving average, weighted moving average, exponential smoothing
    * Multiple-variable forecasting: linear regression
    * Forecasting evaluation: mean absolute deviation, R-squared
    * Extension: Causal inference, machine learning and deep learning
* Project Management:
    * WBS and AON graph
    * Critical path method (CPM)
    * Program evaluation and review technique (PERT)
    * Project crashing
* Inventory Management:
    * Economic order quantity (EOQ) model
    * Production order quantity (POQ) model
    * Quantity discount models
* Linear Programming:
    * Formulation
    * Graphical solution method
    * Integer programming
* Introduction to Monte Carlo Simulation:
    * Functions in Excel
    * Simple examples
    * What-if analysis


***

# Textbooks 

* Required: [Operations Management: Sustainability and Supply Chain Management, 12th Edition](https://www.pearson.com/us/higher-education/product/Heizer-Operations-Management-Sustainability-and-Supply-Chain-Management-12th-Edition/9780134130422.html)
by Jay Heizer, Barry Render, Chuck Munson

***

# Computer Requirements 

A laptop is required, and you are required to be able to run Microsoft Excel (version 2010 is recommended, or later if desired).  You will need to install the Excel OM Software which you can download after you have successfully logged onto MyOMLab, under download center.  
For Mac users, we recommend you to install Windows system first and download the software for PC to avoid potential confusion. The library IT department provides free Windows download for Mac users and assists installation.


***

# Grading

There will be two midterms and one final exam. All exams are non-cumulative. (See tentative schedule)  Homework problems will be assigned on HuskyCT and discussed in class but will not be graded. Short answers to some of them will be provided. Solutions to all other problems can be found on your textbook. It is however, strongly recommended that each student complete each homework in preparation for the quizzes, which will be graded. These quizzes will be based directly on recent homework assignments and will usually be announced in advance. The lowest quiz score will be dropped, allowing some leeway for absentees. In the case of an excused absence (with a note from a doctor) a replacement quiz may be given at the discretion of the instructors. 
Class participation is required and will be evaluated by having in-class assignments that need to be handed at the end of the session. Here is the breakdown of how grades will be evaluated: 

* First Midterm: 25% 
* Second Midterm: 25% 
* Final Examination: 30% 
* Quizzes: 15% 
* Class participation: 5% 

***

# Students with Disabilities

Please contact us during office hours to discuss academic accommodations that may be needed during the semester due to a documented disability. If you have a disability for which you wish to request academic accommodations and have not contacted the Center for Students with Disabilities (CSD), please do so as soon as possible. The CSD engages in an interactive process with each student and reviews requests for accommodations on an individualized, case-by-case basis. The CSD collaborates with students and their faculty to coordinate approved accommodations and services. The CSD is located in Wilbur Cross, Room 204 and can be reached at (860) 486-2020 or at csd@uconn.edu. Detailed information regarding the process to request accommodations is available on the CSD website at https://www.csd.uconn.edu.  

***

# Academic Dishonesty Statement

Behavior that appears to be cheating cannot and will not be tolerated and will be punished appropriately (from earning NO CREDIT on an examination to a failing grade in the class.) 
Behavior that appears to be cheating should be prevented by students and/or reported to the instructors. For every quiz and test there will be at least two different versions, and different versions will be printed on different colored paper, allowing the instructors to visually verify that adjacent students take different versions. This is designed to nullify any benefit of looking at an adjacent student's answers. However, if a student is foolish enough to write down an answer that could only apply to a different version of the quiz/test, that student will automatically receive a failing grade on that quiz/test. 

* [School of Business Academic Honesty Statement](https://users.business.uconn.edu/bday/Honesty.html). 


*** 

# Attendence 

You are expected to attend all lectures and discussions. Failure to do so may not have a direct effect on your course grade, but will likely have a significant indirect effect. Any known or potential extracurricular conflicts should be discussed in person with the instructor during the first week of classes, or as soon as they arise.

*** 

# Disclaimer

The instructors reserve the right to amend, adjust, or otherwise modify this course outline at any time during the course. The students will be notified in a timely fashion of any modification, by email or announcement in class. 
